import { APIGatewayProxyEvent } from 'aws-lambda'

export const eventTemplate: APIGatewayProxyEvent = {
  resource: '/request',
  path: '/request',
  httpMethod: 'GET',
  headers: {
    'X-AMZ-Date': '20231001T000000Z',
    'Accept': 'application/json',
    'Content-Type': 'application/json',
  },
  multiValueHeaders: {},
  queryStringParameters: {
    QueryString1: 'queryValue1',
  },
  multiValueQueryStringParameters: null,
  stageVariables: null,
  requestContext: {
    path: '/dev',
    accountId: '123456789012',
    resourceId: '',
    stage: 'dev',
    domainPrefix: '',
    requestId: '',
    identity: {
      cognitoIdentityPoolId: null,
      cognitoIdentityId: null,
      apiKey: '',
      cognitoAuthenticationType: null,
      userArn: null,
      apiKeyId: '',
      userAgent: '',
      accountId: null,
      caller: null,
      sourceIp: '1.2.3.4',
      accessKey: '',
      cognitoAuthenticationProvider: null,
      user: null,
      clientCert: null,
      principalOrgId: null,
    },
    domainName: '',
    resourcePath: '/',
    httpMethod: 'POST',
    extendedRequestId: '',
    apiId: '',
    authorizer: undefined,
    protocol: '',
    requestTime: '2025/04/01:00:00:00',
    requestTimeEpoch: 123456789,
  },
  body: null,
  isBase64Encoded: false,
  pathParameters: null,
}
